apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        # Notice that actual value for image and tag is set dynamically by helm:
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}        
        ports:
        - containerPort: 80
