apiVersion: apps/v1
#TODO: define the kind of object as Deployment
kind: Deployment
metadata: 
  #TODO: give the deployment a name name: gowebapp-mysql
  name: gowebapp-mysql
  labels:
    #TODO: give the Deployment a label: app: gowebapp-mysql
    #TODO: give the Deployment a label: tier: backend
    app: gowebapp-mysql
    tier: backend
spec:
  #TODO: set replicas to 1
  replicas: 1
  strategy: 
    #TODO: define the type of strategy as Recreate
    type: Recreate
  selector:
    matchLabels:
      app: gowebapp-mysql
      tier: backend
  template:
    metadata:
      labels:
        app: gowebapp-mysql
        tier: backend
    spec:
      containers:
      - name: gowebapp-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mypassword
        image: localhost:5000/gowebapp-mysql:v1 
        ports:
        #TODO: define the container port as 3306
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata: 
  #TODO: give the Service a name: gowebapp-mysql
  name: gowebapp-mysql
  labels:
    #TODO: give the Service a label: app: gowebapp-mysql
    #TODO: give the Service a label: tier: backend
    app: gowebapp-mysql
    tier: backend
spec:
  type: ClusterIP
  ports:
  - #TODO: expose port 3306
    targetPort: 3306
    port: 3306
  selector:
    #TODO: define a selector: app: gowebapp-mysql
    #TODO: define a selector: tier: backend
    app: gowebapp-mysql
    tier: backend