# This associates web-admins-role with a group named web-admins
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-admins-binding
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-admins-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: web-admins